sudo: false

language: python

python:
  - 2.7

cache:
  pip: true
  directories:
    - node_modules

install:
  - pip install -r api/requirements.txt -r api/dev-requirements.txt
  - nvm install 6
  - npm install

script:
  - coverage run api/api_test.py
  - npm test -- --coverage
  - npm run build

after_success:
  - codecov
